version: '3.8'
services:
  jax_diffusion:
    build: .
    image: seasnell/jax_diffusion
    volumes:
     - "./:/app/jax_diffusion/"
    working_dir: /app/
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]